const JobsTableData = [
  {
    id: 1,
    jobs_title: "880 - Cloud Architech",
    priority: "HIGH",
    client: "Augmento",
    experience: 9,
    posted_date: "24-04-2023",
    vacancies: 6,
    location: "Bengaluru",
    associated_candidates: 4,
    contact_person: "Srikant",
    status: "active",
    newlyApplied : [{
      candidateId : "5ede2f28-e572-42c0-8780-aa084c0457dc",
      candidateName : "Walter While",
      email : "abc@gmail.com",
      contactNo : 987654321,
      lastActionOn : "2 days",
      status : "80%",
      location : "Bangaluru",
      skillmatch : "80%"
   },
   {
      candidateId : "5ede2f28-e572-42c0-8780-aa084c0457dc",
      candidateName : "Walter While",
      email : "abc@gmail.com",
      contactNo : 987654321,
      lastActionOn : "2 days",
      status : "80%",
      location : "Bangaluru",
      skillmatch : "80%"
   }
   ],
screening : [{
      candidateId : "5ede2f28-e572-42c0-8780-aa084c0457dc",
      candidateName : "Walter While",
      email : "abc@gmail.com",
      contactNo : 987654321,
      location : "Bangaluru",
      lastActionOn : "2 days",
      status :  ["pending","unknow","scheduled"],
      skillmatch : "80%"
}],
Interview : [{
                    candidateId : "5ede2f28-e572-42c0-8780-aa084c0457dc",
                    candidateName : "Walter While",
                    email : "abc@gmail.com",
                    contactNo : 987654321,
                    location : "Bangaluru",
                    lastActionOn :"2 days",
                    status : ["pending","unknow","scheduled"],
                    skillmatch : "80%"
                }],

Offered : [{
  candidateId : "5ede2f28-e572-42c0-8780-aa084c0457dc",
  candidateName : "Walter While",
  email : "abc@gmail.com",
  contactNo : 987654321,
  location : "Bangaluru",
  lastActionOn : "2023-04-11 16:53:38.09459+05:30",
  status : "pending",
  skillmatch : "80%"
            }],
rejected : [{
  candidateId : "5ede2f28-e572-42c0-8780-aa084c0457dc",
  candidateName : "Walter While",
  email : "abc@gmail.com",
  contactNo : 987654321,
  location : "Bangaluru",
  lastActionOn : "2023-04-11 16:53:38.09459+05:30",
  status : "pending",
  skillmatch : "80%"
             }]

  },
  {
    id: 2,
    jobs_title: "880 - Cloud Architech",
    priority: "HIGH",
    client: "Augmento",
    experience: 9,
    posted_date: "24-04-2023",
    vacancies: 6,
    location: "Bengaluru",
    associated_candidates: 4,
    contact_person: "Srikant",
    status: "active",
  },
  {
    id: 3,
    jobs_title: "880 - Cloud Architech",
    priority: "HIGH",
    client: "Augmento",
    experience: 9,
    posted_date: "24-04-2023",
    vacancies: 6,
    location: "Bengaluru",
    associated_candidates: 4,
    contact_person: "Srikant",
    status: "active",
  },
  {
    id: 4,
    jobs_title: "880 - Cloud Architech",
    priority: "HIGH",
    client: "Augmento",
    experience: 9,
    posted_date: "24-04-2023",
    vacancies: 6,
    location: "Bengaluru",
    associated_candidates: 4,
    contact_person: "Srikant",
    status: "active",
  },
  {
    id: 5,
    jobs_title: "880 - Cloud Architech",
    priority: "HIGH",
    client: "Augmento",
    experience: 9,
    posted_date: "24-04-2023",
    vacancies: 6,
    location: "Bengaluru",
    associated_candidates: 4,
    contact_person: "Srikant",
    status: "active",
  },
];

export default JobsTableData;
